"""
monodromy3d.py -- Synthesis step 1: the boundary configuration of Alpoge's map.

Machine-measures, by numerical continuation of the fiber cubic:
  (1) the local monodromy around the branch surface {A = 0}: a TRANSPOSITION
      of the two colliding sheets (the third sheet is untouched);
  (2) two such loops around different points generate the full S3;
  (3) the escape law: the two colliding sheets have x ~ C * s^{-1/2} as the
      target approaches {A = 0} transversally (square-root wrapping of the
      escaping pair around the boundary divisor at x = infinity).

This is the data card for the 2D non-realizability program: in dimension 2
the boundary of any completion of A^2 is a TREE of rational curves, and the
question is whether this escape/monodromy pattern can be embedded there.
"""
import numpy as np


def cubic_roots(a, b, c):
    """Roots t of P(T) = c T^3 - 2 T^2 + b T - 2a (degree may drop if c=0)."""
    if abs(c) > 1e-14:
        return np.roots([c, -2.0, b, -2.0*a])
    return np.roots([-2.0, b, -2.0*a])


def A_coeff(a, b, c):
    return 27*a**2*c**2 - 18*a*b*c + 16*a + b**3*c - b**2


def continue_roots(path):
    """Track the cubic's roots along a closed path of targets; return the
    permutation matching start to end (nearest-neighbour continuation)."""
    a0, b0, c0 = path[0]
    cur = list(cubic_roots(a0, b0, c0))
    start = list(cur)
    for (a, b, c) in path[1:]:
        new = list(cubic_roots(a, b, c))
        matched = []
        used = [False]*len(new)
        for t in cur:
            j = min((jj for jj in range(len(new)) if not used[jj]),
                    key=lambda jj: abs(new[jj]-t))
            used[j] = True
            matched.append(new[j])
        cur = matched
    perm = []
    for t in cur:
        perm.append(min(range(len(start)), key=lambda i: abs(start[i]-t)))
    return tuple(perm)


def loop_around(base, direction, radius, steps=4000, which=0):
    """Closed loop in target space: base + s*direction, s circling a complex
    root s* of the degree-4 polynomial A(base + s dir) = 0."""
    ss = np.arange(9, dtype=float)
    vals = [A_coeff(*(np.array(base) + s*np.array(direction))) for s in ss]
    coeffs = np.polyfit(ss, vals, 4)
    roots = sorted(np.roots(coeffs), key=abs)
    s_star = roots[which]
    thetas = np.linspace(0, 2*np.pi, steps)
    path = [tuple(np.array(base) + (s_star + radius*np.exp(1j*th))
                  * np.array(direction)) for th in thetas]
    return path, s_star


def main():
    rng = np.random.default_rng(1)
    base = (0.3, 0.4, 0.7)
    assert abs(A_coeff(*base)) > 1e-6

    print("=== local monodromy around {A=0} (all 4 crossings of a line) ===")
    perms = []
    direction = (1.0, 0.3, -0.2)
    for which in range(4):
        path, s_star = loop_around(base, direction, radius=0.006, which=which)
        perm = continue_roots(path)
        fixed = sum(1 for i, p in enumerate(perm) if p == i)
        kind = {3: 'identity', 1: 'TRANSPOSITION', 0: '3-cycle'}[fixed]
        print(f"  crossing #{which}: s*={s_star:.4g}, permutation {perm} -> {kind}")
        assert fixed == 1, "expected a transposition"
        perms.append(perm)

    # do the two transpositions generate S3?
    import itertools
    def compose(p, q):
        return tuple(p[q[i]] for i in range(3))
    G = {(0, 1, 2)}
    frontier = list(perms)
    while frontier:
        g = frontier.pop()
        for h in list(G) + perms:
            for comp in (compose(g, h), compose(h, g)):
                if comp not in G:
                    G.add(comp)
                    frontier.append(comp)
    print(f"  group generated by the loops: order {len(G)} "
          f"({'S3 -- full symmetric' if len(G) == 6 else 'proper subgroup'})")

    print("\n=== escape law: x ~ C * s^(-1/2) toward {A=0} ===")
    direction = (1.0, 0.3, -0.2)
    _, s_star = loop_around(base, direction, radius=0.01)
    ss = s_star - np.geomspace(1e-2, 1e-6, 12)  # complex approach ok
    xs = []
    for s in ss:
        a, b, c = np.array(base) + s*np.array(direction)
        roots = cubic_roots(a, b, c)
        # colliding pair = two closest roots; x = 2/P'(t)
        d = [(abs(roots[i]-roots[j]), i, j)
             for i in range(3) for j in range(i+1, 3)]
        _, i, j = min(d)
        Pp = lambda t: 3*c*t**2 - 4*t + b
        xs.append(max(abs(2/Pp(roots[i])), abs(2/Pp(roots[j]))))
    eps = s_star - ss
    slope = np.polyfit(np.log(eps), np.log(xs), 1)[0]
    print(f"  fit |x| ~ eps^p with p = {slope:.4f}   (theory: -0.5)")
    ok = abs(slope + 0.5) < 0.02
    print(f"  square-root escape law confirmed: {ok}")

    print("\nBOUNDARY DATA CARD (dimension 3):")
    print("  branch divisor {A=0}: local monodromy = transposition;")
    print("  colliding pair escapes to x=infinity with exponent -1/2;")
    print("  loops generate the full S3;")
    print("  over Z (triple-root curve): all three sheets escape (empty fiber).")


if __name__ == '__main__':
    main()
